// COMMON COLUMN NAMES (for DB or API usage)
export const ColumnName = {
  ID: 'id',
  EMAIL: 'email',
  NAME: 'name',
  ROLE: 'role',
  COMPANY_ID: 'company_id',
  CREATED_AT: 'created_at',
  STATUS: 'status',
  TYPE: 'type',
  DESCRIPTION: 'description',
  WELCOME_MESSAGE: 'welcome_message',
  PERSONALITY: 'personality',
  THEME: 'theme',
  IS_ACTIVE: 'is_active',
  API_KEY: 'api_key',
  CHATBOT_ID: 'chatbot_id',
  DATA_SOURCE_ID: 'data_source_id',
  USER_ID: 'user_id',
  MESSAGE: 'message',
  RESPONSE: 'response',
  MESSAGE_TYPE: 'message_type',
  TOKENS_USED: 'tokens_used',
  RESPONSE_TIME_MS: 'response_time_ms',
  UPDATED_AT: 'updated_at',
}; 